FROM ubuntu

# basic packages
RUN \
  apt update && \
  apt -y upgrade && \
  apt install -y build-essential git

# install libnetfilter-conntrack-dev
RUN \
  DEBIAN_FRONTEND=noninteractive apt install -qqy --no-install-recommends \
    libnetfilter-conntrack-dev

# install bazel
RUN \
  apt install -y apt-transport-https curl gnupg && \
  curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg && \
  mv bazel.gpg /etc/apt/trusted.gpg.d/ && \
  echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | \
    tee /etc/apt/sources.list.d/bazel.list && \
  apt update && \
  apt install -y bazel

RUN useradd -rm -d /home/conntrack -s /bin/bash conntrack
USER conntrack
WORKDIR /home/conntrack
CMD ["bash"]
